#
# Copyright (c) 2014 Courierdrone, courierdrone.com
# Distributed under the MIT License, available in the file LICENSE.
# Author: Pavel Kirienko <pavel.kirienko@courierdrone.com>
#

PROJECT = crdr_gps

CSRC = src/sys/board.c

CPPSRC = src/main.cpp                     \
         src/console.cpp

UINCDIR = src/sys

SERIAL_CLI_PORT_NUMBER = 1

include crdr_chibios/rules_stm32f105_107.mk
